spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tmc_db
    username: tmc_user
    password: TMC@2025
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
server:
  servlet:
    session:
      timeout: 15m
app:
  crypto:
    aes-gcm:
      # 32-byte Base64 key for demo
      base64-key: "DYieTKmfVjRXk7KeLNKKJrzzJEz+izQNyXDmbOzTM0s="
      key-id: "c64e5bf1-0958-4936-8586-9b5152c208b9"